version: '3.8'

services:
  db:
    image: postgres:15
    container_name: firefly_iii_postgres_db_local
    restart: unless-stopped
    env_file:
      - .db.env 
    ports:
      - "5432:5432"
    volumes:
      - pgdata_local:/var/lib/postgresql/data
    networks:
      - firefly_local_net

volumes:
  pgdata_local:

networks:
  firefly_local_net:
    driver: bridge