version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: firefly
      POSTGRES_USER: firefly
      POSTGRES_PASSWORD: secret123
    volumes:
      - firefly_db:/var/lib/postgresql/data

  app:
    image: fireflyiii/core:latest
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - firefly_upload:/var/www/html/storage/upload

volumes:
  firefly_db:
  firefly_upload: