services:
  - type: web
    name: firefly-iii
    env: docker
    dockerfilePath: ./Dockerfile.render
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        fromDatabase:
          name: firefly-db
          property: connectionString
      - key: DATABASE_URL
        fromDatabase:
          name: firefly-db
          property: connectionString
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: firefly-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: firefly-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: firefly-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: firefly-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: firefly-db
          property: password

databases:
  - name: firefly-db
    databaseName: firefly
    user: firefly