name: CI with Gitflow

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
      - 'release/**'
      - 'hotfix/**'
  pull_request:
    branches:
      - develop
      - main

jobs:
  test-feature:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/feature/')
    name: Test on Feature
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, dom, pdo, mysql, zip
          tools: composer
          coverage: none

      - name: Validate composer.json and composer.lock files
        run: composer validate --strict

      - name: Get Composer cache directory
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install Composer dependencies
        # El 'if' y el 'run' ahora son parte del mismo paso
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress --no-suggest --no-scripts

      - name: Run Unit Tests with PHPUnit (Backend)
        run: ./vendor/bin/phpunit

  build-and-test-develop:
    if: (github.event_name == 'push' && github.ref == 'refs/heads/develop') || (github.event_name == 'pull_request' && github.base_ref == 'refs/heads/develop')
    name: Build and Test on Develop / PR to Develop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, dom, pdo, mysql, zip
          tools: composer
          coverage: none # La palabra "cobertura" aquí era un error tipográfico, la he eliminado.

      - name: Validate composer.json and composer.lock files
        run: composer validate --strict

      - name: Get Composer cache directory
        id: composer-cache-develop
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install Composer dependencies
        # El 'if' y el 'run' ahora son parte del mismo paso
        if: steps.composer-cache-develop.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress --no-suggest --no-scripts

      - name: Run Unit Tests with PHPUnit (Backend)
        run: ./vendor/bin/phpunit

  build-release-hotfix-and-pr-to-main:
    if: (github.event_name == 'push' && (startsWith(github.ref, 'refs/heads/release/') || startsWith(github.ref, 'refs/heads/hotfix/'))) || (github.event_name == 'pull_request' && github.base_ref == 'refs/heads/main')
    name: Build and Test Release/Hotfix / PR to Main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, dom, pdo, mysql, zip
          tools: composer

      - name: Validate composer.json and composer.lock files
        run: composer validate --strict

      - name: Get Composer cache directory
        id: composer-cache-release
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install Composer dependencies
        # El 'if' y el 'run' ahora son parte del mismo paso
        if: steps.composer-cache-release.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress --no-suggest --optimize-autoloader --no-scripts

      - name: Run Unit Tests with PHPUnit (Backend)
        run: ./vendor/bin/phpunit